---
- name: Database maintenance with dynamic credentials
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Parse dynamic credentials
      set_fact:
        vault_creds: "{{ ansible_env.VAULT_CREDENTIAL | from_json }}"
      when: credential_field == "full_json"
    
    - name: Use username from credential field
      set_fact:
        db_username: "{{ ansible_env.VAULT_CREDENTIAL }}"
      when: credential_field == "username"
    
    - name: Connect to database with dynamic credentials
      postgresql_query:
        host: "{{ database_host }}"
        port: "{{ database_port | default(5432) }}"
        db: "{{ database_name }}"
        login_user: "{{ db_username | default(vault_creds.username) }}"
        login_password: "{{ vault_creds.password }}"
        query: |
          SELECT 
            schemaname,
            tablename,
            attname,
            avg_width,
            n_distinct
          FROM pg_stats 
          WHERE schemaname = 'public'
          ORDER BY tablename, attname;
      register: table_stats
    
    - name: Display table statistics
      debug:
        var: table_stats.query_result
