---
- name: Deploy application with Vault static secrets
  hosts: webservers
  gather_facts: false
  
  tasks:
    - name: Debug Vault secret value
      debug:
        msg: "Retrieved secret length: {{ ansible_env.VAULT_SECRET | length }}"
      
    - name: Use secret in configuration template
      template:
        src: app-config.j2
        dest: /etc/myapp/config.yml
        mode: '0600'
        owner: myapp
        group: myapp
      vars:
        database_password: "{{ ansible_env.VAULT_SECRET }}"
      
    - name: Restart application service
      systemd:
        name: myapp
        state: restarted
        enabled: true
