- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg:
          - "VAULT_SECRET_JSON = {{ lookup('env','VAULT_SECRET_JSON') }}"
          - "VAULT_SECRET_VALUE = {{ lookup('env','VAULT_SECRET_VALUE') }}"
