- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg:
          - "DEBUG_TEST_SECRET_JSON = {{ lookup('env','DEBUG_TEST_SECRET_JSON') }}"
          - "DEBUG_TEST_SECRET_VALUE = {{ lookup('env','DEBUG_TEST_SECRET_VALUE') }}"
