---
- name: Show Vault Azure Dynamic Credential
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show ARM_CLIENT_ID
      debug:
        msg: "ARM_CLIENT_ID: {{ lookup('env', 'ARM_CLIENT_ID') }}"

    - name: Show ARM_CLIENT_SECRET
      debug:
        msg: "ARM_CLIENT_SECRET: {{ lookup('env', 'ARM_CLIENT_SECRET') }}"

    - name: Show ARM_TENANT_ID
      debug:
        msg: "ARM_TENANT_ID: {{ lookup('env', 'ARM_TENANT_ID') }}"

    - name: Show ARM_SUBSCRIPTION_ID
      debug:
        msg: "ARM_SUBSCRIPTION_ID: {{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"
