---
- name: Show Vault AWS Dynamic Credential
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show AWS Access Key
      debug:
        msg: "AWS_ACCESS_KEY_ID: {{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"

    - name: Show AWS Secret Key
      debug:
        msg: "AWS_SECRET_ACCESS_KEY: {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Show AWS Session Token
      debug:
        msg: "AWS_SESSION_TOKEN: {{ lookup('env', 'AWS_SESSION_TOKEN') }}"
