---
- name: Show Vault Static Secret
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Parse VAULT_SECRET_JSON
      set_fact:
        vault_secrets: "{{ lookup('env', 'VAULT_SECRET_JSON') | from_json }}"

    - name: Show all secret keys
      debug:
        var: vault_secrets

    - name: Show specific secret value (if you used secret_key)
      debug:
        msg: "Secret Value: {{ lookup('env', 'VAULT_SECRET_VALUE') }}"
