---
- name: Show Vault Static Secret
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show VAULT_SECRET_JSON
      debug:
        msg: "{{ lookup('env','VAULT_SECRET_JSON') }}"

    - name: Parse VAULT_SECRET_JSON safely
      set_fact:
        vault_secrets: "{{ lookup('env','VAULT_SECRET_JSON') | default('{}') | from_json }}"

    - name: Show all secret keys
      debug:
        var: vault_secrets
