---
- name: Show Vault Database Dynamic Credential
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show DB Username
      debug:
        msg: "DB_USERNAME: {{ lookup('env', 'DB_USERNAME') }}"

    - name: Show DB Password
      debug:
        msg: "DB_PASSWORD: {{ lookup('env', 'DB_PASSWORD') }}"
