---
- name: Show Vault Static Secret
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show all Vault env vars
      debug:
        msg:
          - "VAULT_SECRET_JSON = {{ lookup('env','VAULT_SECRET_JSON') | default('EMPTY') }}"
          - "VAULT_SECRET_VALUE = {{ lookup('env','VAULT_SECRET_VALUE') | default('EMPTY') }}"
