---
- name: Create Vault Credential Types
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx

  tasks:
    - name: Create Vault Secrets Auth type
      awx.awx.credential_type:
        name: Vault Secrets Auth
        kind: cloud
        description: Stores Vault connection and auth config.
        inputs: "{{ lookup('file', 'vault_secrets_auth_credential_type.yml') | from_yaml }}"
        state: present

    - name: Create Vault Secrets Lookup type
      awx.awx.credential_type:
        name: Vault Secrets Lookup
        kind: external
        description: Fetches secrets from Vault.
        plugin: vault_secrets
        inputs: "{{ lookup('file', 'vault_secrets_lookup_credential_type.yml') | from_yaml }}"
        injectors:
          env: {}
        state: present
